# run all the api tests upon creation of a PR on development
name: PR-backend_tests

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up env variables
        run: echo "${{ vars.ENV_FILE }}" > .env

      - name: clean
        run: docker-compose down --volumes --remove-orphans --rmi all

      - name: prune volumes
        run: docker system prune -f --volumes

      - name: build api
        run: docker-compose build api

      - name: run db
        run: docker-compose up -d db

      - name: build worker
        run: docker-compose build worker

      - name: migrate
        run: docker-compose run --rm --entrypoint="python manage.py migrate --no-input" api 

      - name: run worker
        run: docker-compose run -d worker

      - name: run api tests
        run: docker-compose run --rm --entrypoint="pytest -v api" api
